apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-todo-app
  template:
    metadata:
      labels:
        app: go-todo-app
    spec:
      containers:
      - name: go-todo-app
        image: rs11202/go-todo # Ensure this image is built and available
        env:
        - name: DB_HOST
          value: "go-test-db"
        - name: DB_USER
          value: "p4nda"
        - name: DB_PASS
          value: "p4nda_pswd"
        - name: DB_NAME
          value: "go-todo"
        - name: DB_PORT
          value: "5432"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi" # Minimum memory request
            cpu: "100m" # Minimum CPU request
          limits:
            memory: "256Mi" # Maximum memory limit
            cpu: "300m" # Maximum CPU limit

---

apiVersion: v1
kind: Service
metadata:
  name: go-todo-app
spec:
  type: LoadBalancer # or NodePort if LoadBalancer is not supported
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: go-todo-app
